services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TheCodingOwl\OwlCal\:
    resource: '../Classes/*'

  TheCodingOwl\OwlCal\Domain\Repository\UserRepository:
    public: true
